# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '14.0'

target 'AlamofireDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlamofireDemo
  pod 'Alamofire'
  pod 'SQLite.swift', '~> 0.12.0'
end
